// Website-managed taxonomy seed data for X Dental Store.
//
// Brands and categories are owned and managed by the website admin dashboard,
// NOT by the owner/NewAcc system. This list was compiled on 2026-07-07 using the
// public brand/category index of eg.toothpick.com as a reference for names only.
// No layout, images, logos, or marketing copy were copied; optional fields such
// as country, logoUrl, and description are intentionally left blank because no
// reliable data was available. Admins maintain these records from the dashboard.
//
// TODO(taxonomy): the Category model is flat (no parentId). Only top-level
// reference categories are seeded; add parent/child support in the schema before
// seeding subcategories. Promotional pseudo-categories (deals/offers) were excluded.

export const WEBSITE_CATEGORIES = [
  { name: "Restorative", slug: "restorative" },
  { name: "Prosthodontics", slug: "prosthodontics" },
  { name: "Endodontics", slug: "endodontics" },
  { name: "Pedodontics", slug: "pedodontics" },
  { name: "Periodontics", slug: "periodontics" },
  { name: "Orthodontics", slug: "orthodontics" },
  { name: "Implantology", slug: "implantology" },
  { name: "Surgery", slug: "surgery" },
  { name: "Laboratories", slug: "laboratories" },
  { name: "Sterilization Material", slug: "sterilization-material" },
  { name: "Disposable Material", slug: "disposable-material" },
  { name: "Oral Care System", slug: "oral-care-system" },
  { name: "Machines", slug: "machines" },
  { name: "Machine Inquiries", slug: "machine-inquiries" },
  { name: "Radiology", slug: "radiology" },
  { name: "Anesthesia", slug: "anesthesia" },
  { name: "Burs", slug: "burs" },
  { name: "Online Courses", slug: "online-courses" },
  { name: "Others", slug: "others" },
  { name: "Books", slug: "books" },
];

export const WEBSITE_BRANDS = [
  { name: "3B Ortho", slug: "3b-ortho" },
  { name: "3D Shinning", slug: "3d-shinning" },
  { name: "A.Uno", slug: "auno" },
  { name: "A3 Dent", slug: "a3-dent" },
  { name: "Acrostone", slug: "acrostone" },
  { name: "Acteon", slug: "acteon" },
  { name: "Aditek", slug: "aditek" },
  { name: "ADS", slug: "ads" },
  { name: "Aidite", slug: "aidite" },
  { name: "Algines", slug: "algines" },
  { name: "Allaya", slug: "allaya" },
  { name: "Alliedstar", slug: "alliedstar" },
  { name: "Alpha Aire", slug: "alpha-aire" },
  { name: "Alpha Dent", slug: "alpha-dent" },
  { name: "Alpha Endo", slug: "alpha-endo" },
  { name: "ALTTION", slug: "alttion" },
  { name: "Alyarmuk", slug: "alyarmuk" },
  { name: "AmannGirrbach", slug: "amanngirrbach" },
  { name: "Amd Lasers", slug: "amd-lasers" },
  { name: "American Orthodontics", slug: "american-orthodontics" },
  { name: "Anaconda", slug: "anaconda" },
  { name: "Angelus", slug: "angelus" },
  { name: "Anger G&A", slug: "anger-ga" },
  { name: "Anle", slug: "anle" },
  { name: "Anya", slug: "anya" },
  { name: "Aomai", slug: "aomai" },
  { name: "Apex for Medical Wears", slug: "apex-for-medical-wears" },
  { name: "Apixia", slug: "apixia" },
  { name: "Apoza", slug: "apoza" },
  { name: "Appledental", slug: "appledental" },
  { name: "AquaCare", slug: "aquacare" },
  { name: "AR Instrumed", slug: "ar-instrumed" },
  { name: "Ardet", slug: "ardet" },
  { name: "Ark Medical", slug: "ark-medical" },
  { name: "Artech", slug: "artech" },
  { name: "ArteScope", slug: "artescope" },
  { name: "Artman", slug: "artman" },
  { name: "Asa Dental", slug: "asa-dental" },
  { name: "Assut Sutures", slug: "assut-sutures" },
  { name: "ATOS", slug: "atos" },
  { name: "Atria", slug: "atria" },
  { name: "Ats Dental", slug: "ats-dental" },
  { name: "B Chem", slug: "b-chem" },
  { name: "Baioden", slug: "baioden" },
  { name: "BANNA", slug: "banna" },
  { name: "Baolai", slug: "baolai" },
  { name: "Bausch", slug: "bausch" },
  { name: "Bemlase", slug: "bemlase" },
  { name: "Best", slug: "best" },
  { name: "Beta", slug: "beta" },
  { name: "Better Way", slug: "better-way" },
  { name: "Beviston", slug: "beviston" },
  { name: "Beyond", slug: "beyond" },
  { name: "BG Light LTD", slug: "bg-light-ltd" },
  { name: "Bibodent", slug: "bibodent" },
  { name: "Bilumix", slug: "bilumix" },
  { name: "Bioclear", slug: "bioclear" },
  { name: "Biodent", slug: "biodent" },
  { name: "Bioglove", slug: "bioglove" },
  { name: "Biolase", slug: "biolase" },
  { name: "BioMTA", slug: "biomta" },
  { name: "Biotech Dental", slug: "biotech-dental" },
  { name: "Bisco", slug: "bisco" },
  { name: "Bitvae", slug: "bitvae" },
  { name: "Bl.Z Dental", slug: "blz-dental" },
  { name: "Blancone", slug: "blancone" },
  { name: "Blu", slug: "blu" },
  { name: "BlueDent", slug: "bluedent" },
  { name: "BM4", slug: "bm4" },
  { name: "BMS", slug: "bms" },
  { name: "Bomedent", slug: "bomedent" },
  { name: "Bondent", slug: "bondent" },
  { name: "Bookology", slug: "bookology" },
  { name: "Bossklein", slug: "bossklein" },
  { name: "Burite", slug: "burite" },
  { name: "Buzzy", slug: "buzzy" },
  { name: "C-k Dental", slug: "c-k-dental" },
  { name: "C-Root", slug: "c-root" },
  { name: "Cameo", slug: "cameo" },
  { name: "CapKidz", slug: "capkidz" },
  { name: "Caredent", slug: "caredent" },
  { name: "Carestream", slug: "carestream" },
  { name: "Carlo De Giorgi", slug: "carlo-de-giorgi" },
  { name: "Carpo Dental", slug: "carpo-dental" },
  { name: "Castellini", slug: "castellini" },
  { name: "Cavex", slug: "cavex" },
  { name: "Centrix", slug: "centrix" },
  { name: "Ceramic One", slug: "ceramic-one" },
  { name: "Ceyflex", slug: "ceyflex" },
  { name: "Charizard Dental", slug: "charizard-dental" },
  { name: "Cherry Dental", slug: "cherry-dental" },
  { name: "Chifa", slug: "chifa" },
  { name: "Chinese", slug: "chinese" },
  { name: "Chirana", slug: "chirana" },
  { name: "Cingol", slug: "cingol" },
  { name: "CJ Optik", slug: "cj-optik" },
  { name: "CMA", slug: "cma" },
  { name: "Codyson", slug: "codyson" },
  { name: "Coltene", slug: "coltene" },
  { name: "Comfort-in", slug: "comfort-in" },
  { name: "Complete", slug: "complete" },
  { name: "Coral Clean", slug: "coral-clean" },
  { name: "Coredeep", slug: "coredeep" },
  { name: "Corpus Vac", slug: "corpus-vac" },
  { name: "Cotisen", slug: "cotisen" },
  { name: "COXO", slug: "coxo" },
  { name: "Crystal", slug: "crystal" },
  { name: "CX", slug: "cx" },
  { name: "Cy International", slug: "cy-international" },
  { name: "D-Perfect S", slug: "d-perfect-s" },
  { name: "D-Tech", slug: "d-tech" },
  { name: "DB", slug: "db" },
  { name: "DBA", slug: "dba" },
  { name: "De Götzen", slug: "de-gotzen" },
  { name: "Defend", slug: "defend" },
  { name: "Deger", slug: "deger" },
  { name: "DeltaMed", slug: "deltamed" },
  { name: "Dempex", slug: "dempex" },
  { name: "Denject", slug: "denject" },
  { name: "Denjoy", slug: "denjoy" },
  { name: "Denrum Orthodontic", slug: "denrum-orthodontic" },
  { name: "Dentac", slug: "dentac" },
  { name: "DentaFlux", slug: "dentaflux" },
  { name: "Dental Film", slug: "dental-film" },
  { name: "Dental Plus", slug: "dental-plus" },
  { name: "Dental Technologies", slug: "dental-technologies" },
  { name: "Dentalfarm", slug: "dentalfarm" },
  { name: "Dentamaze", slug: "dentamaze" },
  { name: "Dentaurum", slug: "dentaurum" },
  { name: "Dentax", slug: "dentax" },
  { name: "Dentech KSK", slug: "dentech-ksk" },
  { name: "dentex", slug: "dentex" },
  { name: "DentKist", slug: "dentkist" },
  { name: "Dentplus", slug: "dentplus" },
  { name: "Dentra", slug: "dentra" },
  { name: "Dentsply Sirona", slug: "dentsply-sirona" },
  { name: "Denu", slug: "denu" },
  { name: "Deppeler", slug: "deppeler" },
  { name: "Derby", slug: "derby" },
  { name: "Dexis", slug: "dexis" },
  { name: "Dharma", slug: "dharma" },
  { name: "Dia Dent", slug: "dia-dent" },
  { name: "Diamond", slug: "diamond" },
  { name: "Diaswiss", slug: "diaswiss" },
  { name: "Dimed Laser", slug: "dimed-laser" },
  { name: "DM Trust", slug: "dm-trust" },
  { name: "Dmg", slug: "dmg" },
  { name: "DMP", slug: "dmp" },
  { name: "Doctor Scope", slug: "doctor-scope" },
  { name: "Doctorseyes", slug: "doctorseyes" },
  { name: "dolgunn", slug: "dolgunn" },
  { name: "Dota Endo", slug: "dota-endo" },
  { name: "Dr. Kim", slug: "dr-kim" },
  { name: "Dr. Schumacher", slug: "dr-schumacher" },
  { name: "Dr. Smith", slug: "dr-smith" },
  { name: "Dr.Ortho", slug: "drortho" },
  { name: "Drdent", slug: "drdent" },
  { name: "Dream Liner", slug: "dream-liner" },
  { name: "DTC", slug: "dtc" },
  { name: "DTE", slug: "dte" },
  { name: "Durr_Dental", slug: "durr-dental" },
  { name: "DYM", slug: "dym" },
  { name: "DynaFlex", slug: "dynaflex" },
  { name: "E-Press", slug: "e-press" },
  { name: "East Dent", slug: "east-dent" },
  { name: "Easyinsmile", slug: "easyinsmile" },
  { name: "Easysee Egypt", slug: "easysee-egypt" },
  { name: "Edgeendo", slug: "edgeendo" },
  { name: "Egyption", slug: "egyption" },
  { name: "Eighteeth", slug: "eighteeth" },
  { name: "Eksen", slug: "eksen" },
  { name: "El Dawlia Med", slug: "el-dawlia-med" },
  { name: "Elephant", slug: "elephant" },
  { name: "Elexxion", slug: "elexxion" },
  { name: "Elite", slug: "elite" },
  { name: "Ena Hri", slug: "ena-hri" },
  { name: "Endoart", slug: "endoart" },
  { name: "Endostar", slug: "endostar" },
  { name: "ENP", slug: "enp" },
  { name: "Epic", slug: "epic" },
  { name: "ETA Group", slug: "eta-group" },
  { name: "Etadent", slug: "etadent" },
  { name: "Ethicon", slug: "ethicon" },
  { name: "EuroDent", slug: "eurodent" },
  { name: "Euronda", slug: "euronda" },
  { name: "Evony", slug: "evony" },
  { name: "EX", slug: "ex" },
  { name: "Exam Vision", slug: "exam-vision" },
  { name: "EZ-Pac", slug: "ez-pac" },
  { name: "Fanta", slug: "fanta" },
  { name: "FGM", slug: "fgm" },
  { name: "FKG", slug: "fkg" },
  { name: "Flamingo", slug: "flamingo" },
  { name: "Fomos", slug: "fomos" },
  { name: "Fona", slug: "fona" },
  { name: "Forma", slug: "forma" },
  { name: "Fotona", slug: "fotona" },
  { name: "Fourtek", slug: "fourtek" },
  { name: "France", slug: "france" },
  { name: "Fuchs", slug: "fuchs" },
  { name: "Fussen", slug: "fussen" },
  { name: "FYYL Dental", slug: "fyyl-dental" },
  { name: "G&H", slug: "gh" },
  { name: "Galaxy", slug: "galaxy" },
  { name: "Gama Dent", slug: "gama-dent" },
  { name: "Garrison", slug: "garrison" },
  { name: "GC", slug: "gc" },
  { name: "Generic", slug: "generic" },
  { name: "Genoray", slug: "genoray" },
  { name: "Geosoft", slug: "geosoft" },
  { name: "Germ.X", slug: "germx" },
  { name: "Gigaa Laser", slug: "gigaa-laser" },
  { name: "Gingi-Pak", slug: "gingi-pak" },
  { name: "Gladent", slug: "gladent" },
  { name: "Glovesy", slug: "glovesy" },
  { name: "Glydo", slug: "glydo" },
  { name: "GMP", slug: "gmp" },
  { name: "GMS", slug: "gms" },
  { name: "GMT", slug: "gmt" },
  { name: "GNI", slug: "gni" },
  { name: "Godent", slug: "godent" },
  { name: "Gold Plus", slug: "gold-plus" },
  { name: "GoodDrs", slug: "gooddrs" },
  { name: "GuardDent", slug: "guarddent" },
  { name: "GZ", slug: "gz" },
  { name: "Hahnenkratt", slug: "hahnenkratt" },
  { name: "HAN DAE", slug: "han-dae" },
  { name: "Handy", slug: "handy" },
  { name: "Harvard", slug: "harvard" },
  { name: "Headway", slug: "headway" },
  { name: "Heine", slug: "heine" },
  { name: "Henry Schein", slug: "henry-schein" },
  { name: "Hexa", slug: "hexa" },
  { name: "Heydent", slug: "heydent" },
  { name: "Hi Dental Tech", slug: "hi-dental-tech" },
  { name: "Hi-Fill", slug: "hi-fill" },
  { name: "Hirol", slug: "hirol" },
  { name: "Hori", slug: "hori" },
  { name: "Horico", slug: "horico" },
  { name: "Hubit", slug: "hubit" },
  { name: "Huiley", slug: "huiley" },
  { name: "Hulaser", slug: "hulaser" },
  { name: "I-Dental", slug: "i-dental" },
  { name: "IcanClave", slug: "icanclave" },
  { name: "Ice", slug: "ice" },
  { name: "IMD", slug: "imd" },
  { name: "Imicryl", slug: "imicryl" },
  { name: "Indusbello", slug: "indusbello" },
  { name: "Infinity", slug: "infinity" },
  { name: "Intensiv", slug: "intensiv" },
  { name: "Interdent", slug: "interdent" },
  { name: "Ionyx", slug: "ionyx" },
  { name: "IOS", slug: "ios" },
  { name: "IP", slug: "ip" },
  { name: "Ires", slug: "ires" },
  { name: "isorb", slug: "isorb" },
  { name: "Italian", slug: "italian" },
  { name: "Itena", slug: "itena" },
  { name: "Ivoclar Vivadent", slug: "ivoclar-vivadent" },
  { name: "JAINTEK", slug: "jaintek" },
  { name: "Jeep Dental", slug: "jeep-dental" },
  { name: "Jendental", slug: "jendental" },
  { name: "Jerry", slug: "jerry" },
  { name: "Jetax", slug: "jetax" },
  { name: "JG Dental", slug: "jg-dental" },
  { name: "Jinme", slug: "jinme" },
  { name: "JK Dental Vision", slug: "jk-dental-vision" },
  { name: "Johnson Promident", slug: "johnson-promident" },
  { name: "Joident", slug: "joident" },
  { name: "Junwei", slug: "junwei" },
  { name: "K&K", slug: "kk" },
  { name: "Kap", slug: "kap" },
  { name: "Kayan", slug: "kayan" },
  { name: "Keepers Dent", slug: "keepers-dent" },
  { name: "Keju", slug: "keju" },
  { name: "Kemdent", slug: "kemdent" },
  { name: "Kenda", slug: "kenda" },
  { name: "Kerr", slug: "kerr" },
  { name: "Kettenbach", slug: "kettenbach" },
  { name: "Kiato", slug: "kiato" },
  { name: "Kids-e-Dental", slug: "kids-e-dental" },
  { name: "King", slug: "king" },
  { name: "Kingcera", slug: "kingcera" },
  { name: "Koden", slug: "koden" },
  { name: "Kohler", slug: "kohler" },
  { name: "Komet", slug: "komet" },
  { name: "Korea", slug: "korea" },
  { name: "KP", slug: "kp" },
  { name: "Krafit", slug: "krafit" },
  { name: "Kulzer", slug: "kulzer" },
  { name: "Kunshan Adhesive", slug: "kunshan-adhesive" },
  { name: "L&R", slug: "lr" },
  { name: "Lafomed", slug: "lafomed" },
  { name: "LARGEV", slug: "largev" },
  { name: "Larident", slug: "larident" },
  { name: "Lascod", slug: "lascod" },
  { name: "Leone", slug: "leone" },
  { name: "LH", slug: "lh" },
  { name: "Liang Ya", slug: "liang-ya" },
  { name: "Lifebuoy", slug: "lifebuoy" },
  { name: "Linx", slug: "linx" },
  { name: "LM", slug: "lm" },
  { name: "LT MAC", slug: "lt-mac" },
  { name: "Lumix", slug: "lumix" },
  { name: "Lunray", slug: "lunray" },
  { name: "Lunx", slug: "lunx" },
  { name: "Luster Dent", slug: "luster-dent" },
  { name: "Lux Sutures", slug: "lux-sutures" },
  { name: "Lysoform", slug: "lysoform" },
  { name: "Mac Ortho", slug: "mac-ortho" },
  { name: "Madespa", slug: "madespa" },
  { name: "Mailyard", slug: "mailyard" },
  { name: "Malaysia", slug: "malaysia" },
  { name: "Mani", slug: "mani" },
  { name: "Maquira", slug: "maquira" },
  { name: "Marathon", slug: "marathon" },
  { name: "Marathon III", slug: "marathon-iii" },
  { name: "Martina Italy", slug: "martina-italy" },
  { name: "Maruchi", slug: "maruchi" },
  { name: "MAS", slug: "mas" },
  { name: "Matt-Orthodontics", slug: "matt-orthodontics" },
  { name: "Max", slug: "max" },
  { name: "MD Dental", slug: "md-dental" },
  { name: "MDC Dental", slug: "mdc-dental" },
  { name: "Mdclus", slug: "mdclus" },
  { name: "Mecco", slug: "mecco" },
  { name: "Medesy", slug: "medesy" },
  { name: "Medflair", slug: "medflair" },
  { name: "Medic", slug: "medic" },
  { name: "Medicare", slug: "medicare" },
  { name: "Mediclus", slug: "mediclus" },
  { name: "Medin", slug: "medin" },
  { name: "MediWorks", slug: "mediworks" },
  { name: "Medline", slug: "medline" },
  { name: "Mednext", slug: "mednext" },
  { name: "Medpark", slug: "medpark" },
  { name: "Medprotect", slug: "medprotect" },
  { name: "Mega Biodent", slug: "mega-biodent" },
  { name: "Meisinger", slug: "meisinger" },
  { name: "Meite Dental", slug: "meite-dental" },
  { name: "Mera", slug: "mera" },
  { name: "Mercy For Dent", slug: "mercy-for-dent" },
  { name: "Meta Biomed", slug: "meta-biomed" },
  { name: "Metoxit", slug: "metoxit" },
  { name: "Micro - Medica", slug: "micro-medica" },
  { name: "Micro NX", slug: "micro-nx" },
  { name: "Microblaster", slug: "microblaster" },
  { name: "Microdont", slug: "microdont" },
  { name: "Micromega", slug: "micromega" },
  { name: "Miglionico", slug: "miglionico" },
  { name: "Mipont", slug: "mipont" },
  { name: "Miratrade", slug: "miratrade" },
  { name: "Mitex", slug: "mitex" },
  { name: "MK-dent", slug: "mk-dent" },
  { name: "MLG", slug: "mlg" },
  { name: "Mocom", slug: "mocom" },
  { name: "Modern", slug: "modern" },
  { name: "Morita", slug: "morita" },
  { name: "Motranser", slug: "motranser" },
  { name: "Mr Chem", slug: "mr-chem" },
  { name: "NC Endo", slug: "nc-endo" },
  { name: "Neolix", slug: "neolix" },
  { name: "Neoss", slug: "neoss" },
  { name: "New Life Radiology", slug: "new-life-radiology" },
  { name: "NIC", slug: "nic" },
  { name: "nic tone", slug: "nic-tone" },
  { name: "Nordin", slug: "nordin" },
  { name: "NSK", slug: "nsk" },
  { name: "NTI", slug: "nti" },
  { name: "Octa Dent", slug: "octa-dent" },
  { name: "Olident", slug: "olident" },
  { name: "Optek", slug: "optek" },
  { name: "Oradent", slug: "oradent" },
  { name: "Orakit", slug: "orakit" },
  { name: "Orca Dental", slug: "orca-dental" },
  { name: "Orchids", slug: "orchids" },
  { name: "Orikam", slug: "orikam" },
  { name: "Ormco", slug: "ormco" },
  { name: "Oro", slug: "oro" },
  { name: "Orodeka", slug: "orodeka" },
  { name: "Orthmay", slug: "orthmay" },
  { name: "Ortho Classic", slug: "ortho-classic" },
  { name: "Ortho Organizers", slug: "ortho-organizers" },
  { name: "Ortho Xpress", slug: "ortho-xpress" },
  { name: "Orthometric", slug: "orthometric" },
  { name: "OrthoTechnology", slug: "orthotechnology" },
  { name: "Oruite", slug: "oruite" },
  { name: "OT Dent", slug: "ot-dent" },
  { name: "Over Fibers", slug: "over-fibers" },
  { name: "Pakistan", slug: "pakistan" },
  { name: "Panora", slug: "panora" },
  { name: "Parkell", slug: "parkell" },
  { name: "PD", slug: "pd" },
  { name: "PDental", slug: "pdental" },
  { name: "Pearl Beam", slug: "pearl-beam" },
  { name: "Pentron", slug: "pentron" },
  { name: "Perfect Dent", slug: "perfect-dent" },
  { name: "Perfection Plus", slug: "perfection-plus" },
  { name: "Pharaohs", slug: "pharaohs" },
  { name: "Phoco", slug: "phoco" },
  { name: "PicoPack", slug: "picopack" },
  { name: "Pioon", slug: "pioon" },
  { name: "Pippa", slug: "pippa" },
  { name: "Plus", slug: "plus" },
  { name: "Plus Med", slug: "plus-med" },
  { name: "Point", slug: "point" },
  { name: "PoloDent", slug: "polodent" },
  { name: "Polydentia", slug: "polydentia" },
  { name: "Pop", slug: "pop" },
  { name: "Power", slug: "power" },
  { name: "Power Dent", slug: "power-dent" },
  { name: "Pratex", slug: "pratex" },
  { name: "Premia", slug: "premia" },
  { name: "Prevest", slug: "prevest" },
  { name: "Prime Dental", slug: "prime-dental" },
  { name: "Prodent Egypt", slug: "prodent-egypt" },
  { name: "Profa Dental", slug: "profa-dental" },
  { name: "Promedica", slug: "promedica" },
  { name: "Protect", slug: "protect" },
  { name: "Protecta", slug: "protecta" },
  { name: "PSP", slug: "psp" },
  { name: "Pure", slug: "pure" },
  { name: "Puritex", slug: "puritex" },
  { name: "Purity", slug: "purity" },
  { name: "Qartz", slug: "qartz" },
  { name: "Queen Dental", slug: "queen-dental" },
  { name: "R&S", slug: "rs" },
  { name: "Rabbit 3", slug: "rabbit-3" },
  { name: "Ranova", slug: "ranova" },
  { name: "Ray", slug: "ray" },
  { name: "RDT", slug: "rdt" },
  { name: "Reborn Endo", slug: "reborn-endo" },
  { name: "Refine-NSK", slug: "refine-nsk" },
  { name: "Reliance", slug: "reliance" },
  { name: "Remedi", slug: "remedi" },
  { name: "Resinify Technology", slug: "resinify-technology" },
  { name: "Restora Dent", slug: "restora-dent" },
  { name: "Ribbond", slug: "ribbond" },
  { name: "Ristea", slug: "ristea" },
  { name: "Rixi", slug: "rixi" },
  { name: "RMO", slug: "rmo" },
  { name: "RN", slug: "rn" },
  { name: "Rock", slug: "rock" },
  { name: "Rogin Dental", slug: "rogin-dental" },
  { name: "Rolence", slug: "rolence" },
  { name: "RooTA", slug: "roota" },
  { name: "Rose Micro Solutions", slug: "rose-micro-solutions" },
  { name: "Roson", slug: "roson" },
  { name: "Rotex", slug: "rotex" },
  { name: "RTD", slug: "rtd" },
  { name: "Rubydent", slug: "rubydent" },
  { name: "Rundeer", slug: "rundeer" },
  { name: "Runyes", slug: "runyes" },
  { name: "Saeshin", slug: "saeshin" },
  { name: "Sanaden", slug: "sanaden" },
  { name: "Sanctuary", slug: "sanctuary" },
  { name: "Sani", slug: "sani" },
  { name: "Sari Dent", slug: "sari-dent" },
  { name: "Schutz Dental", slug: "schutz-dental" },
  { name: "SciCan", slug: "scican" },
  { name: "SCS", slug: "scs" },
  { name: "SDS", slug: "sds" },
  { name: "Seil Global", slug: "seil-global" },
  { name: "Sendoline", slug: "sendoline" },
  { name: "Shinva", slug: "shinva" },
  { name: "SHM", slug: "shm" },
  { name: "Shofu", slug: "shofu" },
  { name: "Siger", slug: "siger" },
  { name: "SKL", slug: "skl" },
  { name: "Sky", slug: "sky" },
  { name: "Sky Dent", slug: "sky-dent" },
  { name: "SMI", slug: "smi" },
  { name: "SOCO", slug: "soco" },
  { name: "Soga", slug: "soga" },
  { name: "Solase", slug: "solase" },
  { name: "Solo Dam", slug: "solo-dam" },
  { name: "Solventum", slug: "solventum" },
  { name: "SOS", slug: "sos" },
  { name: "Speedjet", slug: "speedjet" },
  { name: "Spident", slug: "spident" },
  { name: "Spine", slug: "spine" },
  { name: "Splash", slug: "splash" },
  { name: "SSWhite", slug: "sswhite" },
  { name: "Stardent", slug: "stardent" },
  { name: "Steri Medical", slug: "steri-medical" },
  { name: "Steristar", slug: "steristar" },
  { name: "SternWeber", slug: "sternweber" },
  { name: "Sun", slug: "sun" },
  { name: "Suntem", slug: "suntem" },
  { name: "Super Pro", slug: "super-pro" },
  { name: "SuperCare", slug: "supercare" },
  { name: "SuperFile", slug: "superfile" },
  { name: "Supermax", slug: "supermax" },
  { name: "Surgicrafts", slug: "surgicrafts" },
  { name: "Surgispon", slug: "surgispon" },
  { name: "Swedent", slug: "swedent" },
  { name: "Syden", slug: "syden" },
  { name: "Taglus", slug: "taglus" },
  { name: "Taisier-Med", slug: "taisier-med" },
  { name: "Task", slug: "task" },
  { name: "TDV", slug: "tdv" },
  { name: "Tealth Foshan", slug: "tealth-foshan" },
  { name: "Tecno-Gaz", slug: "tecno-gaz" },
  { name: "Tehno Dent", slug: "tehno-dent" },
  { name: "Tejan Al Khaleej", slug: "tejan-al-khaleej" },
  { name: "Thomas Tivoly", slug: "thomas-tivoly" },
  { name: "TKD", slug: "tkd" },
  { name: "Toboom", slug: "toboom" },
  { name: "Tokuyama Dental", slug: "tokuyama-dental" },
  { name: "Toothmate", slug: "toothmate" },
  { name: "Top Dental", slug: "top-dental" },
  { name: "Tor Bm", slug: "tor-bm" },
  { name: "Tor VM", slug: "tor-vm" },
  { name: "Toye", slug: "toye" },
  { name: "TP Orthodontics", slug: "tp-orthodontics" },
  { name: "Tpc", slug: "tpc" },
  { name: "Trend", slug: "trend" },
  { name: "Tribest", slug: "tribest" },
  { name: "Trident", slug: "trident" },
  { name: "Tristar", slug: "tristar" },
  { name: "TrollDental", slug: "trolldental" },
  { name: "True Dent", slug: "true-dent" },
  { name: "Trust Dental", slug: "trust-dental" },
  { name: "Twocore", slug: "twocore" },
  { name: "UDG", slug: "udg" },
  { name: "Ultradent", slug: "ultradent" },
  { name: "Unica Group", slug: "unica-group" },
  { name: "Unipro", slug: "unipro" },
  { name: "UP3D", slug: "up3d" },
  { name: "Valuedent", slug: "valuedent" },
  { name: "Vaniman", slug: "vaniman" },
  { name: "Vannini", slug: "vannini" },
  { name: "VDW", slug: "vdw" },
  { name: "Verdent", slug: "verdent" },
  { name: "Vericom", slug: "vericom" },
  { name: "Videya", slug: "videya" },
  { name: "Vigodent", slug: "vigodent" },
  { name: "Vita", slug: "vita" },
  { name: "Voco", slug: "voco" },
  { name: "Voldent", slug: "voldent" },
  { name: "VRN", slug: "vrn" },
  { name: "VSI", slug: "vsi" },
  { name: "W&H", slug: "wh" },
  { name: "Waterpik", slug: "waterpik" },
  { name: "Waterpulse", slug: "waterpulse" },
  { name: "Welco", slug: "welco" },
  { name: "Wellmed", slug: "wellmed" },
  { name: "Whitesmile Flash", slug: "whitesmile-flash" },
  { name: "Wismy", slug: "wismy" },
  { name: "Woodpecker", slug: "woodpecker" },
  { name: "World Work", slug: "world-work" },
  { name: "Woson", slug: "woson" },
  { name: "WP Dental", slug: "wp-dental" },
  { name: "Xpect Vision", slug: "xpect-vision" },
  { name: "Yamakin", slug: "yamakin" },
  { name: "YDA", slug: "yda" },
  { name: "Yes!Star", slug: "yesstar" },
  { name: "Yeson", slug: "yeson" },
  { name: "Yoga", slug: "yoga" },
  { name: "YouJoy", slug: "youjoy" },
  { name: "Yousi", slug: "yousi" },
  { name: "Youtodent", slug: "youtodent" },
  { name: "Zafdent", slug: "zafdent" },
  { name: "Zhermack", slug: "zhermack" },
  { name: "Zogear", slug: "zogear" },
  { name: "Zotion", slug: "zotion" },
  { name: "Zt Dental", slug: "zt-dental" },
  { name: "Zumax", slug: "zumax" },
  { name: "ZZ", slug: "zz" },
];
